development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  domain_name: example.com
  secret_key_base: 5c2d20f4f56f5ba4012e70a9a2a0ad9b0fabfca15a3ffa4e6dc5b5b9df962f9350a544d35b08fefd55f5f1126b04654ac6ba778c7ae165b3234109322dfbefe9

test:
  domain_name: example.com
  secret_key_base: 24359438f877f0167066777d9e57cadfd5f2473430039d1655dd02e40cab6d163f347f65c2cadf41bd1806845f9e4f48fd5335b244324782e85ed548859decd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: Admin
  admin_email: ehtishamqasmi@gmail.com
  admin_password: ehti11572
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  domain_name: etrendz.in
  secret_key_base: 5c2d20f4f56f5ba4012e70a9a2a0ad9b0fabfca15a3ffa4e6dc5b5b9df962f9350a544d35b08fefd55f5f1126b04654ac6ba778c7ae165b3234109322dfbefe9
